"""
Multi-Agent Support Router (MASR) - Execution Steps
=============================================================================
File:        run.py
Required:    agent_graph.py
Description: includes dependencies and steps to run the agents

Author:      Adam Santone, PhD
Date:        June 2026
License:     MIT License
=============================================================================
"""

# include dependencies
import os
from langchain_core.messages import HumanMessage

# Import the compiled graph app from your first file
from agent_graph import app

# Define the incoming customer problem
# content defines the human-authored problem statement
incoming_ticket = {
    "messages": [
        HumanMessage(content="My API requests keep dropping with a 504 timeout error.")
    ]
}

OUTPUT_FILENAME = "synthesized_customer_response.txt"

print("====================================================")
print("Initializing Multi-Agent Support Router (MASR)...")
print("Running diagnostic workflow via local Ollama instance...")
print("====================================================\n")

# Variable to track the final cumulative state payload
final_state_output = {}

# 3. Execute the graph and stream live progress milestones to the console
for output in app.stream(incoming_ticket):
    for node, value in output.items():
        print(f"✦ Active Node Processing: [{node.upper()}]")
        for key, content in value.items():
            if content:
                # Capture the state updates into our local tracking variable
                final_state_output[key] = content
                # Print a clean, brief preview to show activity
                preview = str(content)[:80].replace('\n', ' ')
                print(f"  └─ Captured [{key}]: {preview}...\n")

print("====================================================")
print("Diagnostic run complete. Processing file export...")
print("====================================================")

# 4. Intercept the final response payload and export it to a local text file
# Using utf-8 encoding ensures that quotes, dashes, and bullet points render perfectly.
try:
    final_response_text = final_state_output.get("final_response", "Error: No response generated by agents.")
    
    with open(OUTPUT_FILENAME, "w", encoding="utf-8") as text_file:
        text_file.write(final_response_text)
        
    print(f"✔ Success! Customer response: {os.path.abspath(OUTPUT_FILENAME)}")
    print("====================================================")

except Exception as e:
    print(f"✘ Operational Error writing final text file: {str(e)}")